# SveltiaCMS Configuration
# Documentation: https://github.com/sveltia/sveltia-cms
# local_backend: true
backend:
  name: git-gateway

#   name: github # Change to your backend (github, gitlab, gitea)
#   repo: gafemoyano/afuera-del-cuadrito # Replace with your repository
#   branch: main # or master, depending on your default branch

# Media files
media_folder: "public/images/uploads" # Where uploaded files will be stored
public_folder: "/images/uploads" # Public URL path for uploaded files

# Site configuration
site_url: https://afuera-del-cuadrito.netlify.app # Replace with your site URL
logo_url: /images/logo.png

# Collections
collections:
  # Blog Posts
  - name: "posts"
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Meta Title",
          name: "meta_title",
          widget: "string",
          required: false,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - label: "Categories"
        name: "categories"
        widget: "list"
        default: ["general"]
        field: { label: "Category", name: "category", widget: "string" }
      - label: "Authors"
        name: "authors"
        widget: "relation"
        collection: "authors"
        search_fields: ["title"]
        display_fields: ["title"]
        value_field: "title"
        multiple: true
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # Authors
  - name: "authors"
    label: "Authors"
    label_singular: "Author"
    folder: "src/content/authors"
    create: true
    slug: "{{slug}}"
    filter: { field: "title", value: "" } # Exclude index files
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - {
          label: "Meta Title",
          name: "meta_title",
          widget: "string",
          required: false,
        }
      - { label: "Profile Image", name: "image", widget: "image" }
      - { label: "Bio", name: "description", widget: "text" }
      - label: "Social Links"
        name: "social"
        widget: "object"
        required: false
        fields:
          - {
              label: "Facebook",
              name: "facebook",
              widget: "string",
              required: false,
            }
          - {
              label: "Twitter",
              name: "twitter",
              widget: "string",
              required: false,
            }
          - {
              label: "Instagram",
              name: "instagram",
              widget: "string",
              required: false,
            }
          - {
              label: "LinkedIn",
              name: "linkedin",
              widget: "string",
              required: false,
            }
          - {
              label: "Website",
              name: "website",
              widget: "string",
              required: false,
            }
      - { label: "About", name: "body", widget: "markdown", required: false }

  # Pages
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Meta Title",
          name: "meta_title",
          widget: "string",
          required: false,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # Special Pages (using file collection for singleton pages)
  - name: "special_pages"
    label: "Special Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/content/about/-index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Meta Title",
              name: "meta_title",
              widget: "string",
              required: false,
            }
          - {
              label: "Description",
              name: "description",
              widget: "text",
              required: false,
            }
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "Draft", name: "draft", widget: "boolean", default: false }
          - { label: "Content", name: "body", widget: "markdown" }

# Editor settings
editor:
  preview: true

# Display URL for site preview
display_url: https://afuera-del-cuadrito.netlify.app # Replace with your site URL
